name: Wayclip CLI publish to AUR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set Environment from Tag and API
        run: |
          echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

          echo "Fetching latest core version..."
          CORE_TAG=$(curl -s "https://api.github.com/repos/Wayclip/core/releases/latest" | jq -r '.tag_name')
          if [ -z "$CORE_TAG" ] || [ "$CORE_TAG" == "null" ]; then
            echo "Error: Failed to fetch latest core tag from GitHub API."
            exit 1
          fi
          echo "CORE_VER=${CORE_TAG#v}" >> $GITHUB_ENV
          echo "Using Core version: ${CORE_TAG#v}"

      - name: Generate PKGBUILD
        run: |
          cat <<EOF > PKGBUILD
          # Maintainer: konyogony <dev@wayclip.com>
          pkgname=wayclip-cli
          pkgver=${PKG_VER}
          pkgrel=1
          pkgdesc="The CLI interface for Wayclip, an instant replay tool built for the Linux community."
          arch=('x86_64')
          url="https://github.com/wayclip/cli"
          license=('MIT')
          depends=('bzip2' 'elfutils' 'gstreamer' 'glib2' 'libffi' 'libunwind' 'openssl' 'pcre2' 'util-linux-libs' 'xz' 'zlib' 'zstd')
          makedepends=('rust' 'cargo')
          provides=('wayclip')
          conflicts=('wayclip')

          source=("\$pkgname-\$pkgver.tar.gz::\${url}/archive/refs/tags/v\$pkgver.tar.gz"
                  "wayclip-core.tar.gz::https://github.com/Wayclip/core/archive/refs/tags/v${CORE_VER}.tar.gz"
                  "wayclip-daemon.service")

          sha256sums=('SKIP'
                      'SKIP'
                      'SKIP')

          prepare() {
            tar -xzf "\$srcdir/\$pkgname-\$pkgver.tar.gz" -C "\$srcdir/"
            tar -xzf "\$srcdir/wayclip-core.tar.gz" -C "\$srcdir/"
          }

          build() {
            local core_dir="core-v${CORE_VER}"

            export CFLAGS+=" -ffat-lto-objects"
            export CXXFLAGS+=" -ffat-lto-objects"
            export RUSTUP_TOOLCHAIN=stable

            cd "\$srcdir/\$core_dir"
            cargo build --release --locked
            mv target/release/daemon "\$srcdir/daemon"
            mv target/release/trigger "\$srcdir/trigger"

            cd "\$srcdir/\$pkgname-\$pkgver"
            cargo build --release --locked
          }

          check() {
            cd "\$srcdir/\$pkgname-\$pkgver"
            cargo test
          }

          package() {
            install -Dm755 "\$srcdir/\$pkgname-\$pkgver/target/release/wayclip" "\$pkgdir/usr/bin/wayclip"

            install -Dm755 "\$srcdir/daemon" "\$pkgdir/usr/bin/wayclip-daemon"
            install -Dm755 "\$srcdir/trigger" "\$pkgdir/usr/bin/wayclip-trigger"

            install -Dm644 "\$srcdir/wayclip-daemon.service" "\$pkgdir/usr/lib/systemd/user/wayclip-daemon.service"
          }
          EOF

      - name: Update PKGBUILD and push to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgbuild: ./PKGBUILD
          pkgname: "wayclip-cli"
          assets: "wayclip-daemon.service"
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version v${{ env.PKG_VER }}"
          updpkgsums: "true"
