name: Wayclip CLI publish to AUR and Release AppImage

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-22.04
    outputs:
      artifact-path: release_binaries
    steps:
      - name: Checkout CLI repository
        uses: actions/checkout@v4
        with:
          path: cli

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install system dependencies
        run: |
          sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream -y
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libglib2.0-dev libssl-dev libpq-dev libssh2-1-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavfilter-dev libavdevice-dev libswresample-dev \
            libwayland-dev libxkbcommon-dev libpipewire-0.3-dev libdbus-1-dev \
            libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libx11-dev libxrandr-dev libxtst-dev libasound2-dev libfuse2 wget

      - name: Set Environment from Tag and API
        run: |
          echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          CORE_TAG=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Wayclip/core/releases/latest" | jq -r '.tag_name')
          echo "CORE_VER=${CORE_TAG#v}" >> $GITHUB_ENV

      - name: Download and Extract Core release tarball
        run: |
          mkdir -p core
          TARBALL_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/Wayclip/core/releases/latest" | \
            jq -r '.assets[] | select(.name == "wayclip-v${{ env.CORE_VER }}-x86_64-unknown-linux-gnu.tar.gz") | .browser_download_url')
          curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$TARBALL_URL" | tar -xzf - -C core

      - name: Build CLI binary
        run: |
          cd cli
          cargo build --release
          cd ..
          mkdir -p release_binaries
          cp cli/target/release/wayclip_cli release_binaries/
          cp core/wayclip-binaries/daemon release_binaries/
          cp core/wayclip-binaries/trigger release_binaries/

      - name: Generate PKGBUILD
        run: |
          cat <<EOF > PKGBUILD
          pkgname=wayclip-cli
          pkgver=${{ env.PKG_VER }}
          pkgrel=1
          pkgdesc="CLI for Wayclip"
          arch=('x86_64')
          url="https://github.com/wayclip/cli"
          license=('MIT')
          depends=('bzip2' 'elfutils' 'gstreamer' 'glib2' 'libffi' 'libunwind' 'openssl' 'pcre2' 'util-linux-libs' 'xz' 'zlib' 'zstd' 'pipewire')
          makedepends=('rust' 'cargo')
          source=("\$pkgname-\$pkgver.tar.gz::\$url/archive/refs/tags/v\$pkgver.tar.gz"
                  "wayclip-core.tar.gz::https://github.com/Wayclip/core/releases/download/v${{ env.CORE_VER }}/wayclip-v${{ env.CORE_VER }}-x86_64-unknown-linux-gnu.tar.gz")
          sha256sums=('SKIP' 'SKIP')
          prepare() { tar -xzf "\$srcdir/\$pkgname-\$pkgver.tar.gz" -C "\$srcdir/"; tar -xzf "\$srcdir/wayclip-core.tar.gz" -C "\$srcdir/"; }
          build() { cd "\$srcdir/cli-\$pkgver"; cargo build --release; }
          package() { install -Dm755 "\$srcdir/cli-\$pkgver/target/release/wayclip_cli" "\$pkgdir/usr/bin/wayclip-cli"; install -Dm755 "\$srcdir/wayclip-binaries/daemon" "\$pkgdir/usr/bin/wayclip-daemon"; install -Dm755 "\$srcdir/wayclip-binaries/trigger" "\$pkgdir/usr/bin/wayclip-trigger"; }
          EOF

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_binaries
          path: release_binaries
      - uses: actions/upload-artifact@v4
        with:
          name: PKGBUILD
          path: PKGBUILD

      - name: Build AppImage
        run: |
          mkdir -p AppDir/usr/bin
          cp release_binaries/* AppDir/usr/bin/
          cp cli/assets/wayclip-cli.desktop AppDir/
          cp cli/assets/wayclip-cli.png AppDir/
          chmod +x AppDir/usr/bin/*
          cat <<EOF > AppDir/AppRun
          #!/bin/sh
          exec "\$APPDIR/usr/bin/wayclip_cli" "\$@"
          EOF
          chmod +x AppDir/AppRun
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage
      - uses: actions/upload-artifact@v4
        with:
          name: AppImage
          path: wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage

  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release_binaries
          path: release_binaries
      - uses: actions/download-artifact@v4
        with:
          name: PKGBUILD
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: AppImage
          path: .

      - name: Test PKGBUILD in Arch container
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace archlinux:latest bash -c "\
            pacman-key --init && pacman-key --populate archlinux && pacman -Sy --noconfirm base-devel git && \
            makepkg --printsrcinfo && makepkg -si --noconfirm && wayclip-cli --version \
          "

      - name: Test AppImage
        run: ./wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage --version

  deploy:
    runs-on: ubuntu-22.04
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: PKGBUILD
          path: .
      - uses: actions/download-artifact@v4
        with:
          name: AppImage
          path: .

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgbuild: ./PKGBUILD
          pkgname: wayclip-cli
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update to version v${{ env.PKG_VER }}
          ssh_keyscan_types: rsa,ecdsa,ed25519

      - name: Upload AppImage to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
