name: Wayclip CLI publish to AUR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get version from tag
        id: get_version
        run: echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update PKGBUILD and push to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2
        env:
          INPUT_SSH_KEYSCAN_TYPES: "rsa,dsa,ecdsa,ed25519"
          INPUT_PKGNAME: "wayclip-cli"
          INPUT_COMMIT_USERNAME: ${{ secrets.AUR_USERNAME }}
          INPUT_COMMIT_EMAIL: ${{ secrets.AUR_EMAIL }}
          INPUT_SSH_PRIVATE_KEY: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          INPUT_COMMIT_MESSAGE: "Update to version v${{ env.PKG_VER }}"
          INPUT_UPDPKGSUMS: "true"
          INPUT_PKGBUILD: |
            # Maintainer: konyogony <dev@wayclip.com>
            pkgname=wayclip-cli
            pkgver=${{ env.PKG_VER }}
            pkgrel=1
            pkgdesc="The CLI interface for Wayclip, an instant replay tool built for the Linux community."
            arch=('x86_64')
            url="https://github.com/wayclip/cli"
            license=('MIT')
            depends=('bzip2' 'elfutils' 'gstreamer' 'glib2' 'libffi' 'libunwind' 'openssl' 'pcre2' 'util-linux-libs' 'xz' 'zlib' 'zstd')
            makedepends=('rust' 'cargo')

            source=("$pkgname-$pkgver.tar.gz::${url}/archive/refs/tags/v${pkgver}.tar.gz"
                    "wayclip-core.tar.gz::https://github.com/Wayclip/core/releases/download/v${pkgver}/wayclip-v${pkgver}-x86_64-unknown-linux-gnu.tar.gz"
                    "wayclip-daemon.service")

            sha256sums=('SKIP'
                        'SKIP'
                        'SKIP')

            prepare() {
              cd "$srcdir/cli-$pkgver"
            }

            build() {
              cd "$srcdir/cli-$pkgver"
              export RUSTUP_TOOLCHAIN=stable
              cargo build --release --locked
            }

            check() {
              cd "$srcdir/cli-$pkgver"
              cargo test --locked
            }

            package() {
              cd "$srcdir/cli-$pkgver"
              install -Dm755 "target/release/wayclip_cli" "$pkgdir/usr/bin/wayclip-cli"

              install -Dm755 "$srcdir/daemon" "$pkgdir/usr/bin/wayclip-daemon"
              install -Dm755 "$srcdir/trigger" "$pkgdir/usr/bin/wayclip-trigger"

              install -Dm644 "$srcdir/wayclip-daemon.service" "$pkgdir/usr/lib/systemd/user/wayclip-daemon.service"
            }
