name: Wayclip CLI publish to AUR and Release AppImage

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout CLI repository
        uses: actions/checkout@v4
        with:
          path: cli

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install build dependencies
        run: |
          sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream -y
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libglib2.0-dev libssl-dev libpq-dev libssh2-1-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavfilter-dev libavdevice-dev libswresample-dev \
            libwayland-dev libxkbcommon-dev libpipewire-0.3-dev libdbus-1-dev libspa-0.2-dev \
            libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libx11-dev libasound2-dev libfuse2 wget jq

      - name: Set Environment from Tag and API
        run: |
          echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          CORE_TAG=$(curl -s "https://api.github.com/repos/Wayclip/core/releases/latest" | jq -r '.tag_name')
          echo "CORE_TAG_FULL=${CORE_TAG}" >> $GITHUB_ENV

      - name: Build the CLI binary
        run: cd cli && cargo build --release

      - name: Prepare Release Assets
        run: |
          mkdir release_assets
          cp cli/target/release/wayclip-cli release_assets/wayclip-cli-x86_64-unknown-linux-gnu
          cp cli/assets/wayclip-daemon.service release_assets/

      - name: Build AppImage
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/lib/systemd/user
          cp cli/target/release/wayclip-cli AppDir/usr/bin/wayclip-cli
          cp cli/assets/wayclip-cli.desktop AppDir/
          cp cli/assets/wayclip-cli.png AppDir/
          cp cli/assets/wayclip-daemon.service AppDir/usr/lib/systemd/user/
          chmod +x AppDir/usr/bin/wayclip-cli
          cat <<EOF > AppDir/AppRun
          #!/bin/sh
          exec "\$APPDIR/usr/bin/wayclip-cli" "\$@"
          EOF
          chmod +x AppDir/AppRun
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir
          mv Wayclip_CLI-x86_64.AppImage release_assets/wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage

      - name: Generate correct PKGBUILD for AUR
        run: |
          cat <<'EOF' > PKGBUILD
          # Maintainer: konyogony <dev@wayclip.com>
          pkgname=wayclip-cli
          pkgver=${{ env.PKG_VER }}
          pkgrel=1
          pkgdesc="The CLI interface for Wayclip, an instant replay tool built for the Linux community."
          arch=('x86_64')
          url="https://github.com/Wayclip/cli"
          license=('MIT')
          depends=('pipewire' 'wayland' 'alsa-lib' 'ffmpeg' 'gstreamer' 'gst-plugins-base' 'dbus' 'libxcb')
          makedepends=('rust' 'cargo' 'clang' 'git')

          _core_ver="${{ env.CORE_TAG_FULL }}"
          source=("$pkgname-$pkgver.tar.gz::https://github.com/Wayclip/cli/archive/refs/tags/v$pkgver.tar.gz"
                  "wayclip-core.tar.gz::https://github.com/Wayclip/core/releases/download/$_core_ver/wayclip-$_core_ver-x86_64-unknown-linux-gnu.tar.gz")
          sha256sums=('SKIP' 'SKIP')

          prepare() {
              mv "$srcdir/cli-$pkgver" "$srcdir/$pkgname-$pkgver"
          }

          build() {
              cd "$srcdir/$pkgname-$pkgver"
              cargo build --release
          }

          package() {
              install -Dm755 "$srcdir/$pkgname-$pkgver/target/release/wayclip-cli" "$pkgdir/usr/bin/wayclip-cli"

              install -Dm755 "$srcdir/wayclip-binaries/daemon" "$pkgdir/usr/bin/wayclip-daemon"
              install -Dm755 "$srcdir/wayclip-binaries/trigger" "$pkgdir/usr/bin/wayclip-trigger"

              sed -i 's|__WAYCLIP_DAEMON_PATH__|/usr/bin/wayclip-daemon|' "$srcdir/$pkgname-$pkgver/assets/wayclip-daemon.service"
              install -Dm644 "$srcdir/$pkgname-$pkgver/assets/wayclip-daemon.service" "$pkgdir/usr/lib/systemd/user/wayclip-daemon.service"
          }
          EOF
          mv PKGBUILD release_assets/

      - name: Upload artifacts for deploy job
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: release_assets/

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-release
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-assets

      - name: Set Environment from Tag
        run: echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgbuild: ./PKGBUILD
          pkgname: wayclip-cli
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version v${{ env.PKG_VER }}"

      - name: Upload Assets to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wayclip-cli-*.AppImage
            wayclip-cli-x86_64-unknown-linux-gnu
            wayclip-daemon.service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
