name: Wayclip CLI publish to AUR

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get CLI version from tag
        id: get_cli_version
        run: echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Get latest core version
        run: |
          CORE_TAG=$(curl -s https://api.github.com/repos/Wayclip/core/releases/latest | jq -r '.tag_name')
          echo "CORE_VER=${CORE_TAG#v}" >> $GITHUB_ENV

      - name: Generate PKGBUILD
        run: |
          cat <<EOF > PKGBUILD
          # Maintainer: konyogony <dev@wayclip.com>
          pkgname=wayclip-cli
          pkgver=${PKG_VER}
          pkgrel=1
          pkgdesc="The CLI interface for Wayclip, an instant replay tool built for the Linux community."
          arch=('x86_64')
          url="https://github.com/wayclip/cli"
          license=('MIT')
          depends=('bzip2' 'elfutils' 'gstreamer' 'glib2' 'libffi' 'libunwind' 'openssl' 'pcre2' 'util-linux-libs' 'xz' 'zlib' 'zstd')
          makedepends=('rust' 'cargo')

          source=("\$pkgname-\$pkgver.tar.gz::\${url}/archive/refs/tags/v\${pkgver}.tar.gz"
                  "wayclip-core.tar.gz::https://github.com/Wayclip/core/releases/download/v${CORE_VER}/wayclip-v${CORE_VER}-x86_64-unknown-linux-gnu.tar.gz"
                  "wayclip-daemon.service")

          sha256sums=('SKIP'
                      'SKIP'
                      'SKIP')

          prepare() {
            cd "\$srcdir/cli-\$pkgver"
          }

          build() {
            cd "\$srcdir/cli-\$pkgver"
            export CFLAGS+=" -ffat-lto-objects"
            export CXXFLAGS+=" -ffat-lto-objects"
            export RUSTUP_TOOLCHAIN=stable
            cargo build --release
          }

          check() {
            cd "\$srcdir/cli-\$pkgver"
            cargo test
          }

          package() {
            cd "\$srcdir/cli-\$pkgver"
            install -Dm755 "target/release/wayclip_cli" "\$pkgdir/usr/bin/wayclip-cli"

            install -Dm755 "\$srcdir/daemon" "\$pkgdir/usr/bin/wayclip-daemon"
            install -Dm755 "\$srcdir/trigger" "\$pkgdir/usr/bin/wayclip-trigger"

            install -Dm644 "\$srcdir/wayclip-daemon.service" "\$pkgdir/usr/lib/systemd/user/wayclip-daemon.service"
          }
          EOF

      - name: Update PKGBUILD and push to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgbuild: ./PKGBUILD
          pkgname: "wayclip-cli"
          assets: "wayclip-daemon.service"
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version v${{ env.PKG_VER }}"
          updpkgsums: "true"
          ssh_keyscan_types: "rsa,ecdsa,ed25519"
          post_process: rm -f "wayclip-cli-${{ env.PKG_VER }}.tar.gz" "wayclip-core.tar.gz"
