name: Wayclip CLI publish to AUR and Release AppImage

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout CLI repository
        uses: actions/checkout@v4
        with:
          path: cli

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install build dependencies
        run: |
          sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream -y
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libglib2.0-dev libssl-dev libpq-dev libssh2-1-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavfilter-dev libavdevice-dev libswresample-dev \
            libwayland-dev libxkbcommon-dev libpipewire-0.3-dev libdbus-1-dev libspa-0.2-dev \
            libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libx11-dev libasound2-dev libfuse2 wget jq bsdmainutils

      - name: Set Environment from Tag and API
        run: |
          echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          CORE_TAG=$(curl -s "https://api.github.com/repos/Wayclip/core/releases/latest" | jq -r '.tag_name')
          echo "CORE_TAG_FULL=${CORE_TAG}" >> $GITHUB_ENV
          CORE_VER=$(echo $CORE_TAG | sed 's/v//')
          echo "CORE_VER=${CORE_VER}" >> $GITHUB_ENV

      - name: Download and Extract Core Binaries
        run: |
          mkdir core-binaries
          CORE_ASSET_URL="https://github.com/Wayclip/core/releases/download/${{ env.CORE_TAG_FULL }}/wayclip-${{ env.CORE_VER }}-x86_64-unknown-linux-gnu.tar.gz"
          echo "Downloading core binaries from ${CORE_ASSET_URL}"
          wget -q -O core-binaries.tar.gz "${CORE_ASSET_URL}"
          tar -xzf core-binaries.tar.gz -C core-binaries
          echo "Extracted core binaries:"
          ls -l core-binaries

      - name: Build the CLI binary
        run: cd cli && cargo build --release

      - name: Prepare Release Assets
        run: |
          mkdir release_assets
          cp cli/target/release/wayclip-cli release_assets/wayclip-cli-x86_64-unknown-linux-gnu
          cp core-binaries/wayclip-daemon release_assets/
          cp core-binaries/wayclip-trigger release_assets/
          cp cli/assets/wayclip-daemon.service release_assets/

      - name: Build AppImage
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/lib/systemd/user
          cp cli/target/release/wayclip-cli AppDir/usr/bin/wayclip-cli
          cp core-binaries/wayclip-daemon AppDir/usr/bin/wayclip-daemon
          cp core-binaries/wayclip-trigger AppDir/usr/bin/wayclip-trigger
          cp cli/assets/wayclip-cli.desktop AppDir/
          cp cli/assets/wayclip-cli.png AppDir/
          cp cli/assets/wayclip-daemon.service AppDir/usr/lib/systemd/user/
          sed -i 's|ExecStart=.*|ExecStart=%h/.local/bin/wayclip-daemon|' AppDir/usr/lib/systemd/user/wayclip-daemon.service
          chmod +x AppDir/usr/bin/*
          cat <<'EOF' > AppDir/AppRun
          #!/bin/sh
          exec "$APPDIR/usr/bin/wayclip-cli" "$@"
          EOF
          chmod +x AppDir/AppRun
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir
          mv Wayclip_CLI-x86_64.AppImage release_assets/wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage

      - name: Generate correct PKGBUILD for AUR
        run: |
          cat <<'PKG' > PKGBUILD.in
          pkgname=wayclip-cli
          pkgver=@PKG_VER@
          pkgrel=1
          pkgdesc="The CLI interface for Wayclip, an instant replay tool built for the Linux community."
          arch=('x86_64')
          url="https://github.com/Wayclip/cli"
          license=('MIT')
          depends=('pipewire' 'wayland' 'alsa-lib' 'ffmpeg' 'gstreamer' 'gst-plugins-base' 'dbus' 'libxcb')
          makedepends=('rust' 'cargo' 'clang' 'git')
          _core_ver="@CORE_TAG@"
          _core_ver_num_only=$(echo "${_core_ver}" | sed 's/v//')
          source=("$pkgname-$pkgver.tar.gz::https://github.com/Wayclip/cli/archive/refs/tags/v$pkgver.tar.gz"
                  "wayclip-core.tar.gz::https://github.com/Wayclip/core/releases/download/${_core_ver}/wayclip-${_core_ver_num_only}-x86_64-unknown-linux-gnu.tar.gz")
          sha256sums=('SKIP' 'SKIP')

          prepare() {
            if [ -d "$srcdir/cli-$pkgver" ]; then
              mv "$srcdir/cli-$pkgver" "$srcdir/$pkgname-$pkgver"
            fi
            mkdir -p "$srcdir/wayclip-core"
            bsdtar -xvf "$srcdir/wayclip-core.tar.gz" -C "$srcdir/wayclip-core"
          }

          build() {
            cd "$srcdir/$pkgname-$pkgver"
            cargo build --release
          }

          package() {
            cd "$srcdir/$pkgname-$pkgver"
            install -Dm755 "target/release/wayclip-cli" "$pkgdir/usr/bin/wayclip-cli"
            core_bin_dir="$srcdir/wayclip-core"
            for n in daemon trigger; do
              if [ -f "$core_bin_dir/$n" ]; then
                install -Dm755 "$core_bin_dir/$n" "$pkgdir/usr/bin/wayclip-$n"
              else
                echo "ERROR: Did not find the '$n' binary in $core_bin_dir!"
                return 1
              fi
            done
            if [ -f "assets/wayclip-daemon.service" ]; then
              sed -i 's|ExecStart=.*|ExecStart=/usr/bin/wayclip-daemon|' "assets/wayclip-daemon.service"
              install -Dm644 "assets/wayclip-daemon.service" "$pkgdir/usr/lib/systemd/user/wayclip-daemon.service"
            fi
          }
          PKG
          sed -e "s|@PKG_VER@|${PKG_VER}|g" -e "s|@CORE_TAG@|${CORE_TAG_FULL}|g" PKGBUILD.in > PKGBUILD
          rm PKGBUILD.in
          mv PKGBUILD release_assets/

      - name: Upload artifacts for deploy job
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: release_assets/

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-release
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-assets

      - name: Set Environment from Tag
        run: echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgbuild: ./PKGBUILD
          pkgname: wayclip-cli
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version v${{ env.PKG_VER }}"

      - name: Upload Assets to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release_assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
