name: Wayclip CLI publish to AUR and Release AppImage

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Set Environment from Trigger
        id: set_env
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Triggered by push tag: ${{ github.ref_name }}"
            CLI_VERSION_TAG="${{ github.ref_name }}"
          else
            echo "Triggered by '${{ github.event_name }}'. Finding latest CLI release tag."
            CLI_VERSION_TAG=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r '.tag_name')
            if [[ -z "$CLI_VERSION_TAG" || "$CLI_VERSION_TAG" == "null" ]]; then
              echo "::error::Could not determine the latest CLI release tag."
              exit 1
            fi
            echo "Found latest CLI release tag to rebuild: $CLI_VERSION_TAG"
          fi

          echo "Fetching latest core release tag..."
          CORE_TAG=$(curl -s "https://api.github.com/repos/Wayclip/core/releases/latest" | jq -r '.tag_name')
          if [[ -z "$CORE_TAG" || "$CORE_TAG" == "null" ]]; then
            echo "::error::Could not determine the latest core release tag."
            exit 1
          fi
          echo "Found latest core release tag: $CORE_TAG"

          echo "PKG_VER=${CLI_VERSION_TAG#refs/tags/v}" >> $GITHUB_ENV
          echo "CLI_TAG_REF=${CLI_VERSION_TAG}" >> $GITHUB_ENV
          echo "CORE_TAG_FULL=${CORE_TAG}" >> $GITHUB_ENV

      - name: Checkout CLI repository at correct tag
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CLI_TAG_REF }}
          path: cli

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install build dependencies
        run: |
          sudo add-apt-repository ppa:pipewire-debian/pipewire-upstream -y
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential pkg-config libglib2.0-dev libssl-dev libpq-dev libssh2-1-dev \
            libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libavfilter-dev libavdevice-dev libswresample-dev \
            libwayland-dev libxkbcommon-dev libpipewire-0.3-dev libdbus-1-dev libspa-0.2-dev \
            libunwind-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
            libx11-dev libasound2-dev libfuse2 wget jq bsdmainutils

      - name: Download and Extract Core Binaries
        run: |
          mkdir core-binaries
          CORE_ASSET_URL="https://github.com/Wayclip/core/releases/download/${{ env.CORE_TAG_FULL }}/wayclip-${{ env.CORE_TAG_FULL }}-x86_64-unknown-linux-gnu.tar.gz"
          echo "Downloading core binaries from ${CORE_ASSET_URL}"
          wget -q -O core-binaries.tar.gz "${CORE_ASSET_URL}"
          tar -xzf core-binaries.tar.gz -C core-binaries
          echo "Extracted core binaries:"
          ls -lR core-binaries

      - name: Build the CLI binary
        run: cd cli && cargo build --release

      - name: Prepare Release Assets
        run: |
          mkdir release_assets
          cp cli/target/release/wayclip-cli release_assets/wayclip-cli-x86_64-unknown-linux-gnu
          cp core-binaries/wayclip-binaries/daemon release_assets/wayclip-daemon
          cp core-binaries/wayclip-binaries/trigger release_assets/wayclip-trigger
          cp cli/assets/wayclip-daemon.service release_assets/

      - name: Build AppImage
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/lib/systemd/user
          cp release_assets/wayclip-cli-x86_64-unknown-linux-gnu AppDir/usr/bin/wayclip-cli
          cp release_assets/wayclip-daemon AppDir/usr/bin/wayclip-daemon
          cp release_assets/wayclip-trigger AppDir/usr/bin/wayclip-trigger
          cp cli/assets/wayclip-cli.desktop AppDir/
          cp cli/assets/wayclip-cli.png AppDir/
          cp release_assets/wayclip-daemon.service AppDir/usr/lib/systemd/user/
          sed -i 's|ExecStart=.*|ExecStart=%h/.local/bin/wayclip-daemon|' AppDir/usr/lib/systemd/user/wayclip-daemon.service
          chmod +x AppDir/usr/bin/*
          cat <<'EOF' > AppDir/AppRun
          #!/bin/sh
          exec "$APPDIR/usr/bin/wayclip-cli" "$@"
          EOF
          chmod +x AppDir/AppRun
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir
          mv Wayclip_CLI-x86_64.AppImage release_assets/wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage

      - name: Generate correct PKGBUILD for AUR
        run: |
          cat <<'PKG' > PKGBUILD.in
          # Maintainer: konyogony <dev@wayclip.com>
          pkgname=wayclip-cli
          pkgver=@PKG_VER@
          pkgrel=1
          pkgdesc="The CLI interface for Wayclip, an instant replay tool built for the Linux community."
          arch=('x86_64')
          url="https://github.com/Wayclip/cli"
          license=('MIT')
          depends=('pipewire' 'wayland' 'alsa-lib' 'ffmpeg' 'gstreamer' 'gst-plugins-base' 'dbus' 'libxcb' 'jq')
          makedepends=('rust' 'cargo' 'curl')
          source=("$pkgname-$pkgver.tar.gz::https://github.com/Wayclip/cli/archive/refs/tags/v$pkgver.tar.gz")
          sha256sums=('SKIP')

          prepare() {
            cd "$srcdir"
            
            echo "Fetching the latest core release information from GitHub..."
            local core_api_url="https://api.github.com/repos/Wayclip/core/releases/latest"
            
            local core_release_data=$(curl -s "$core_api_url")
            _core_ver=$(echo "$core_release_data" | jq -r '.tag_name')
            local core_download_url=$(echo "$core_release_data" | jq -r --arg ver "$_core_ver" '.assets[] | select(.name == "wayclip-\($ver)-x86_64-unknown-linux-gnu.tar.gz") | .browser_download_url')

            if [ -z "$_core_ver" ] || [ "$_core_ver" == "null" ] || [ -z "$core_download_url" ] || [ "$core_download_url" == "null" ]; then
              echo "::error::Could not determine the latest core release tag or download URL."
              exit 1
            fi
            
            echo "Downloading core binaries version ${_core_ver} from ${core_download_url}..."
            curl -L -o "wayclip-core-binaries.tar.gz" "$core_download_url"
            
            tar -xzf "wayclip-core-binaries.tar.gz"
          }

          build() {
            cd "$srcdir/cli-$pkgver"
            cargo build --release
          }

          package() {
            install -Dm755 "$srcdir/cli-$pkgver/target/release/wayclip-cli" "$pkgdir/usr/bin/wayclip-cli"
            
            install -Dm755 "$srcdir/wayclip-binaries/daemon" "$pkgdir/usr/bin/wayclip-daemon"
            install -Dm755 "$srcdir/wayclip-binaries/trigger" "$pkgdir/usr/bin/wayclip-trigger"
            
            if [ -f "$srcdir/cli-$pkgver/assets/wayclip-daemon.service" ]; then
              sed -i 's|ExecStart=.*|ExecStart=/usr/bin/wayclip-daemon|' "$srcdir/cli-$pkgver/assets/wayclip-daemon.service"
              install -Dm644 "$srcdir/cli-$pkgver/assets/wayclip-daemon.service" "$pkgdir/usr/lib/systemd/user/wayclip-daemon.service"
            fi
          }
          PKG
          sed -e "s|@PKG_VER@|${PKG_VER}|g" PKGBUILD.in > PKGBUILD
          rm PKGBUILD.in
          mv PKGBUILD release_assets/

      - name: Upload artifacts for deploy job
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: release_assets/

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-release
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-assets

      - name: Set Environment from downloaded artifacts
        run: |
          echo "PKG_VER=$(grep -oP 'pkgver=\K.*' PKGBUILD)" >> $GITHUB_ENV
          echo "CORE_TAG_FULL=$(grep -oP '_core_ver=\K.*' PKGBUILD)" >> $GITHUB_ENV

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgbuild: ./PKGBUILD
          pkgname: wayclip-cli
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to v${{ env.PKG_VER }} (core: ${{ env.CORE_TAG_FULL }})"

      - name: Upload Assets to GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage
            wayclip-cli-x86_64-unknown-linux-gnu
            wayclip-daemon
            wayclip-trigger
            wayclip-daemon.service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
