name: Wayclip CLI publish to AUR and Release AppImage

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout CLI repository
        uses: actions/checkout@v4
        with:
          path: cli

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libfuse2

      - name: Set Environment from Tag and API
        run: |
          echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
          CORE_TAG=$(curl -s "https://api.github.com/repos/Wayclip/core/releases/latest" | jq -r '.tag_name')
          echo "CORE_TAG_FULL=${CORE_TAG}" >> $GITHUB_ENV

      - name: Build the CLI binary
        run: cd cli && cargo build --release

      - name: Build AppImage
        run: |
          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/lib/systemd/user

          cp cli/target/release/wayclip_cli AppDir/usr/bin/wayclip-cli

          cp cli/assets/wayclip-cli.desktop AppDir/
          cp cli/assets/wayclip-cli.png AppDir/
          cp cli/assets/wayclip-daemon.service AppDir/usr/lib/systemd/user/

          chmod +x AppDir/usr/bin/wayclip-cli

          cat <<EOF > AppDir/AppRun
          #!/bin/sh
          exec "\$APPDIR/usr/bin/wayclip-cli" "\$@"
          EOF
          chmod +x AppDir/AppRun

          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage
          ARCH=x86_64 ./appimagetool-x86_64.AppImage AppDir wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage

      - name: Generate correct PKGBUILD for AUR
        run: |
          cat <<'EOF' > PKGBUILD
          # Maintainer: konyogony <dev@wayclip.com>
          pkgname=wayclip-cli
          pkgver=${{ env.PKG_VER }}
          pkgrel=1
          pkgdesc="The CLI interface for Wayclip, an instant replay tool built for the Linux community."
          arch=('x86_64')
          url="https://github.com/Wayclip/cli"
          license=('MIT')
          depends=('bzip2' 'elfutils' 'glib2' 'libffi' 'libunwind' 'openssl' 'pcre2' 'util-linux-libs' 'xz' 'zlib' 'zstd' 'pipewire' 'wayland' 'alsa-lib' 'ffmpeg' 'gstreamer' 'gst-plugins-base' 'gst-plugins-good' 'gst-plugins-bad' 'postgresql-libs' 'dbus' 'libxcb')
          makedepends=('rust' 'cargo' 'clang' 'git')

          _core_ver="${{ env.CORE_TAG_FULL }}"
          source=("$pkgname-$pkgver.tar.gz::https://github.com/Wayclip/cli/archive/refs/tags/v$pkgver.tar.gz"
                  "wayclip-core.tar.gz::https://github.com/Wayclip/core/releases/download/$_core_ver/wayclip-$_core_ver-x86_64-unknown-linux-gnu.tar.gz")
          sha256sums=('SKIP' 'SKIP')

          prepare() {
              tar -xzf "$srcdir/$pkgname-$pkgver.tar.gz"
              
              mkdir -p "$srcdir/wayclip-core-binaries"
              tar -xzf "$srcdir/wayclip-core.tar.gz" -C "$srcdir/wayclip-core-binaries" --strip-components=1
          }

          build() {
              cd "$srcdir/cli-$pkgver"
              cargo build --release
          }

          package() {
              install -Dm755 "$srcdir/cli-$pkgver/target/release/wayclip_cli" "$pkgdir/usr/bin/wayclip-cli"
              install -Dm755 "$srcdir/wayclip-core-binaries/wayclip-binaries/daemon" "$pkgdir/usr/bin/wayclip-daemon"
              install -Dm755 "$srcdir/wayclip-core-binaries/wayclip-binaries/trigger" "$pkgdir/usr/bin/wayclip-trigger"
              
              install -Dm644 "$srcdir/cli-$pkgver/assets/wayclip-daemon.service" "$pkgdir/usr/lib/systemd/user/wayclip-daemon.service"
          }
          EOF

      - name: Upload artifacts for deploy job
        uses: actions/upload-artifact@v4
        with:
          name: release-assets
          path: |
            wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage
            PKGBUILD

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-release
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: release-assets

      - name: Set Environment from Tag
        run: echo "PKG_VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Publish to AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgbuild: ./PKGBUILD
          pkgname: wayclip-cli
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: "Update to version v${{ env.PKG_VER }}"

      - name: Upload Assets to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wayclip-cli-${{ env.PKG_VER }}-x86_64.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
